# Generated by Django 2.1.2 on 2019-10-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191021_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='address',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='固定电话'),
        ),
    ]
